#!/usr/bin/env node
// Phase 8 — Architecture Diagram Generator.
// Renders tests/phase-8/diagram.html (self-contained dark-theme SVG).
// Run: node tests/phase-8/runtime/render-diagram.mjs

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);

const KERNELS = ['capability', 'acquisition', 'publishing', 'recovery', 'insights'];
const KERNEL_COLORS = {
  capability:  '#7dd3fc',
  acquisition: '#fcd34d',
  publishing:  '#f9a8d4',
  recovery:    '#a7f3d0',
  insights:    '#c4b5fd',
};

const W = 1200, H = 720;
const COL_X = (i) => 200 + i * 200;
const ROW_Y = (i) => 240 + i * 70;

function kernelNode(x, y, name) {
  return `
    <g class="kernel" transform="translate(${x},${y})">
      <circle r="42" fill="${KERNEL_COLORS[name]}" fill-opacity="0.18" stroke="${KERNEL_COLORS[name]}" stroke-width="2"/>
      <text text-anchor="middle" dy="6" fill="${KERNEL_COLORS[name]}" font-size="14" font-weight="600">${name}</text>
    </g>`;
}

function arc(src, dst, idx) {
  const sx = COL_X(KERNELS.indexOf(src));
  const sy = ROW_Y(idx);
  const dx = COL_X(KERNELS.indexOf(dst));
  const dy = ROW_Y(idx);
  const mx = (sx + dx) / 2;
  const my = sy - 60 - idx * 6;
  return `<path d="M${sx + 50},${sy} Q${mx},${my} ${dx - 50},${dy}" fill="none" stroke="#94a3b8" stroke-width="1" stroke-dasharray="3 3" opacity="0.55"/>
          <text x="${mx}" y="${my - 4}" text-anchor="middle" fill="#cbd5e1" font-size="10">${src}→${dst}</text>`;
}

const wires = [];
let idx = 0;
for (const s of KERNELS) {
  for (const d of KERNELS) {
    if (s === d) continue;
    wires.push(arc(s, d, idx++));
  }
}

const nodes = KERNELS.map((k, i) => kernelNode(COL_X(i), 480, k)).join('\n');

const constitutionalA = `
  <g class="flow-a" transform="translate(60,80)">
    <text x="0" y="0" fill="#e2e8f0" font-size="14" font-weight="600">Constitutional Path A — Webhook → State</text>
    <g transform="translate(0,30)">
      ${['Webhook (9200)', 'Ingress', 'Parser', 'Governance', 'FSM', 'Worker', 'State'].map((label, i) => `
        <g transform="translate(${i * 150},0)">
          <rect width="130" height="44" rx="6" fill="#0f172a" stroke="#38bdf8" stroke-width="1.5"/>
          <text x="65" y="27" text-anchor="middle" fill="#e2e8f0" font-size="12">${label}</text>
          ${i < 6 ? `<path d="M130,22 L150,22" stroke="#38bdf8" stroke-width="1.5"/>` : ''}
        </g>`).join('')}
    </g>
  </g>`;

const constitutionalB = `
  <g class="flow-b" transform="translate(60,640)">
    <text x="0" y="0" fill="#e2e8f0" font-size="14" font-weight="600">Constitutional Path B — Graph → State</text>
    <g transform="translate(0,30)">
      ${['Graph (9100)', 'Worker', 'Governance', 'State'].map((label, i) => `
        <g transform="translate(${i * 200},0)">
          <rect width="180" height="44" rx="6" fill="#0f172a" stroke="#fcd34d" stroke-width="1.5"/>
          <text x="90" y="27" text-anchor="middle" fill="#e2e8f0" font-size="12">${label}</text>
          ${i < 3 ? `<path d="M180,22 L200,22" stroke="#fcd34d" stroke-width="1.5"/>` : ''}
        </g>`).join('')}
    </g>
  </g>`;

const html = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>Phase 8 — Cross-Kernel Communication Diagram</title>
  <style>
    body { margin: 0; padding: 24px; background: #020617; color: #e2e8f0; font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif; }
    h1 { font-size: 18px; margin: 0 0 4px 0; color: #f1f5f9; }
    .sub { color: #94a3b8; font-size: 12px; margin-bottom: 16px; }
    .card { background: #0b1220; border: 1px solid #1e293b; border-radius: 8px; padding: 16px; }
    .legend { font-size: 11px; color: #94a3b8; margin-top: 12px; }
    svg { display: block; max-width: 100%; height: auto; }
  </style>
</head>
<body>
  <h1>Phase 8 — Cross-Kernel Communication Diagram</h1>
  <div class="sub">Generated by tests/phase-8/runtime/render-diagram.mjs — ${KERNELS.length} kernels, ${wires.length} cross-kernel wires, 2 constitutional flow paths.</div>
  <div class="card">
    <svg viewBox="0 0 ${W} ${H}" xmlns="http://www.w3.org/2000/svg">
      <rect width="${W}" height="${H}" fill="#020617"/>
      ${wires.join('\n')}
      ${nodes}
      ${constitutionalA}
      ${constitutionalB}
    </svg>
  </div>
  <div class="legend">
    Each colored circle is a kernel. Dashed gray arcs are the 20 cross-kernel wires (every source→sink pair except self). The two horizontal bands are the constitutional flow paths validated by phase-8.
  </div>
</body>
</html>`;

const out = path.join(__dirname, '..', 'diagram.html');
fs.writeFileSync(out, html);
console.log('[render-diagram] wrote ' + out);
