// substrates/webhook-acquisition-substrate/workers/messages-worker.js
// Worker: Instagram DM webhook semantics.
//   - DM echo (entry[].messaging[].message)
//   - DM postback (entry[].messaging[].postback)
//
// Mounted on: substrates/ig-reliability-substrate.js (analyzeFailure).
// Lives in:  acquisition-kernel/substrates/webhook-acquisition-substrate/workers/.
//
// Owns: validates entry[].messaging[] shape, normalizes via the substrate's
//        normalizer, dispatches the canonical event to CK so the
//        acquisition-fsm can hold it. Phase 2 will resolve the staged
//        event into DB_WRITE_REQUESTED.
// Does NOT own: failure classification (bedrock), DB writes, retry policy,
//               state persistence, token storage.
//
// Constitutional contract: workers never classify IG failures directly.
// On any processing error the worker asks the bedrock for an analysis and
// emits the substrate's recommendations through CK.

const { analyzeFailure } =
  require('../../../../substrates/ig-reliability-substrate');
const { normalizeMessaging, EVENT_TYPES } = require('../normalizer');
const { WorkerStateMachine } = require('./_state-machine');

const WORKER_DOMAIN = 'webhook:messages';
const WORKER_EVENT_TYPE = EVENT_TYPES.DM_ECHO;

// ── Validation helpers (semantic shape checks for the worker) ─────────────

function _validateMessagingEntry(item) {
  if (!item || typeof item !== 'object') {
    return { ok: false, reason: 'messaging_item_not_object' };
  }
  if (!item.sender?.id) {
    return { ok: false, reason: 'missing_sender_id' };
  }
  if (!item.recipient?.id) {
    return { ok: false, reason: 'missing_recipient_id' };
  }
  const hasMessage = !!item.message;
  const hasPostback = !!item.postback;
  if (!hasMessage && !hasPostback) {
    return { ok: false, reason: 'messaging_item_has_no_message_or_postback' };
  }
  if (hasMessage && !item.message.mid) {
    return { ok: false, reason: 'missing_message_mid' };
  }
  if (hasPostback && !item.postback.mid) {
    return { ok: false, reason: 'missing_postback_mid' };
  }
  return { ok: true };
}

// ── Worker contract ─────────────────────────────────────────────────────────

/**
 * Execute: process one entry[].messaging[] item into a canonical event
 * and dispatch it into CK for the acquisition-fsm to hold.
 *
 * @param {object} rawItem    — single entry[].messaging[] element
 * @param {string} accountId  — resolved IG account id (from entry.id)
 * @param {string} intentId   — unique intent id generated by the substrate
 * @param {object} governance — constitutional kernel reference
 * @returns {Promise<{ status: string, eventId: string|null, eventType: string }>}
 */
async function execute(rawItem, accountId, intentId, governance) {
  const wstate = new WorkerStateMachine({
    accountId, intentId, eventType: WORKER_EVENT_TYPE,
    domain: WORKER_DOMAIN, governance,
  });

  wstate.transition('VALIDATING');
  const v = _validateMessagingEntry(rawItem);
  if (!v.ok) {
    wstate.transition('FAILED_VALIDATION', v.reason);
    return _emitFailure(rawItem, accountId, intentId, v.reason, governance);
  }

  wstate.transition('NORMALIZING');
  let canonical;
  try {
    canonical = normalizeMessaging(rawItem, null);
    canonical.igAccountId = accountId || null;
  } catch (err) {
    wstate.transition('FAILED_NORMALIZE', err.message);
    return _emitFailure(rawItem, accountId, intentId, `normalizer_threw:${err.message}`, governance);
  }

  wstate.transition('DISPATCHING');
  try {
    if (governance && typeof governance.dispatch === 'function') {
      governance.dispatch({
        type: 'WEBHOOK_EVENT_RECEIVED',
        lineageId: `webhook:acquisition:${intentId}`,
        lineageDomain: 'acquisition',
        accountId,
        intentId,
        domain: WORKER_DOMAIN,
        eventType: canonical.eventType,
        eventId: canonical.eventId,
        occurredAt: canonical.occurredAt,
        source: canonical.source,
        priority: canonical.priority,
        normalized: canonical.normalized,
        raw: canonical.raw,
      });
    }
  } catch (err) {
    wstate.transition('FAILED_DISPATCH', err.message);
    return _emitFailure(rawItem, accountId, intentId, `dispatch_threw:${err.message}`, governance);
  }

  wstate.transition('STAGED');
  return {
    status: 'staged',
    eventId: canonical.eventId,
    eventType: canonical.eventType,
  };
}

// ── Failure emission via the bedrock (no in-worker classification) ─────────

function _emitFailure(rawItem, accountId, intentId, reason, governance) {
  // Build a minimal error envelope for analyzeFailure. The bedrock expects
  // { message } at minimum; the substrate will normalize + classify it.
  const rawError = {
    message: reason,
    source: 'webhook-acquisition:messages',
    eventType: EVENT_TYPES.DM_ECHO,
  };

  let recommendations = [];
  try {
    const analysis = analyzeFailure(rawError, 'webhook:process', 'webhook-acquisition', {
      accountId,
      intentId,
      eventType: 'dm_echo',
    });
    recommendations = analysis?.recommendations || [];
  } catch (_) {
    // Bedrock failure should not block the substrate from emitting a
    // fallback signal. The substrate contract is best-effort.
    recommendations = [];
  }

  if (governance && typeof governance.dispatch === 'function') {
    try {
      governance.dispatch({
        type: 'WEBHOOK_EVENT_DISCARDED',
        lineageId: `webhook:acquisition:discarded:${intentId}`,
        lineageDomain: 'acquisition',
        accountId,
        intentId,
        domain: WORKER_DOMAIN,
        eventType: WORKER_EVENT_TYPE,
        reason,
        recommendations,
      });
    } catch (_) {
      // Swallow — the failure path is informational.
    }
  }

  return {
    status: 'discarded',
    eventId: null,
    eventType: WORKER_EVENT_TYPE,
    reason,
  };
}

module.exports = { execute };
